In [10]:
!pip install yfinance requests beautifulsoup4 matplotlib

Requirement already satisfied: yfinance in c:\users\saiful\anaconda3\lib\site-packages (0.2.50)
Requirement already satisfied: requests in c:\users\saiful\anaconda3\lib\site-packages (2.32.2)
Requirement already satisfied: beautifulsoup4 in c:\users\saiful\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: matplotlib in c:\users\saiful\anaconda3\lib\site-packages (3.8.4)
Requirement already satisfied: pandas>=1.3.0 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (5.2.1)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (3.17.8)
Requirement already satisfied: html5lib>=1.1 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\saiful\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saiful\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saiful\anaconda3\lib\site-packages (from requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saiful\anaconda3\lib\site-packages (from requests) (2024.8.30)
Requirement already satisfied: soupsieve>1.2 in c:\users\saiful\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\saiful\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.9 in c:\users\saiful\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\saiful\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saiful\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)

In [12]:
!pip install yfinance

Requirement already satisfied: yfinance in c:\users\saiful\anaconda3\lib\site-packages (0.2.50)
Requirement already satisfied: pandas>=1.3.0 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (2.32.2)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (5.2.1)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (3.17.8)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in c:\users\saiful\anaconda3\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\saiful\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in c:\users\saiful\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\saiful\anaconda3\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saiful\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saiful\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\saiful\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saiful\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saiful\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saiful\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2024.8.30)

In [13]:
import yfinance as yf

# Extract Tesla stock data
tesla_stock = yf.Ticker('TSLA')
tesla_data = tesla_stock.history(period='1y')  # Fetch data for the past year

# Display the first few rows of the data
tesla_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-11-22 00:00:00-05:00,242.039993,244.009995,231.399994,234.210007,117950600,0.0,0.0
2023-11-24 00:00:00-05:00,233.750000,238.750000,232.330002,235.449997,65125200,0.0,0.0
2023-11-27 00:00:00-05:00,236.889999,238.330002,232.100006,236.080002,112031800,0.0,0.0
2023-11-28 00:00:00-05:00,236.679993,247.000000,234.009995,246.720001,148549900,0.0,0.0
2023-11-29 00:00:00-05:00,249.210007,252.750000,242.759995,244.139999,135401300,0.0,0.0

In [14]:
import yfinance as yf


# Extract Tesla stock data
tesla_stock = yf.Ticker('TSLA')
tesla_data = tesla_stock.history(period='1y')  # Fetch data for the past year

# Display the first few rows of the data
tesla_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-11-22 00:00:00-05:00,242.039993,244.009995,231.399994,234.210007,117950600,0.0,0.0
2023-11-24 00:00:00-05:00,233.750000,238.750000,232.330002,235.449997,65125200,0.0,0.0
2023-11-27 00:00:00-05:00,236.889999,238.330002,232.100006,236.080002,112031800,0.0,0.0
2023-11-28 00:00:00-05:00,236.679993,247.000000,234.009995,246.720001,148549900,0.0,0.0
2023-11-29 00:00:00-05:00,249.210007,252.750000,242.759995,244.139999,135401300,0.0,0.0

In [25]:
# Extract GameStop stock data
gamestop_stock = yf.Ticker('GME')
gamestop_data = gamestop_stock.history(period='1y')  # Fetch data for the past year

# Display the first few rows of the data
gamestop_data.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-11-22 00:00:00-05:00,12.56,12.710000,12.19,12.29,2358800,0.0,0.0
2023-11-24 00:00:00-05:00,12.22,12.410000,12.18,12.20,1232500,0.0,0.0
2023-11-27 00:00:00-05:00,12.18,12.330000,11.89,11.91,3710600,0.0,0.0
2023-11-28 00:00:00-05:00,11.90,13.550000,11.89,13.49,14192900,0.0,0.0
2023-11-29 00:00:00-05:00,15.49,17.559999,14.70,16.25,61172800,0.0,0.0

In [20]:
import requests
from bs4 import BeautifulSoup

# URL for GameStop's financials on Yahoo Finance
url = 'https://finance.yahoo.com/quote/GME/financials?p=GME'

# Send GET request to fetch the page content
response = requests.get(url)

# Check if request was successful
if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'html.parser')

    # Extract the table containing financials
    tables = soup.find_all('table')
    if len(tables) > 1:  # Ensure there is a table for the financial data
        table = tables[1]  # The second table contains the revenue data

        # Loop through rows and extract relevant data
        gamestop_revenue = []
        for row in table.find_all('tr')[1:]:  # Skip the header row
            cols = row.find_all('td')
            if len(cols) > 1:  # Ensure there are at least two columns
                year = cols[0].text.strip()
                rev = cols[1].text.strip()
                gamestop_revenue.append([year, rev])

        # Print extracted revenue data
        for item in gamestop_revenue:
            print(item)
    else:
        print("Error: Could not find the revenue table on the webpage.")
else:
    print(f"Error: Unable to fetch the page. Status code: {response.status_code}")

Error: Unable to fetch the page. Status code: 404